---
name: Release
# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - dropwizard-foundationdb-*
jobs:
  release:
    uses: dropwizard/workflows/.github/workflows/release.yml@03157308cef2eae58551c4ef12ae4f901c0134c1 # main
    secrets: inherit
